import argparse
import random
import time

import torch
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

from configs import CFG
from envs.thor_objnav_env import ThorObjNavEnv
from envs.scene_split import TARGETS
from models.resnet_encoder import ResNet50Encoder
from models.word2vec_embed import WordEmbed
from models.osm import OSM
from models.omt_transformer import OMTTransformer

'''
python demo.py \
  --w2v-table /home/hekanwei/gensim-data/thor_w2v_table.npz \
  --model ppo_omt4_thor.zip
'''

KITCHEN_SCENES = [f"FloorPlan{i}" for i in range(1, 21)]


def make_demo_env(w2v_table: str | None):
    """Single-environment, visualized (headless=False) demo env.

    Args:
        w2v_table: Path to precomputed w2v table (.npz). If provided, the demo will
            NOT load the 3.4GB GoogleNews vectors.
    """
    device = "cuda" if torch.cuda.is_available() else "cpu"

    # feature modules (same as training)
    resnet = ResNet50Encoder(device=device)

    if w2v_table:
        print(f"[W2V] Using table: {w2v_table}", flush=True)
        embed = WordEmbed(table_path=w2v_table)
    else:
        # Fallback (not recommended): may try to load heavy GoogleNews vectors.
        print("[W2V] WARNING: no --w2v-table provided; WordEmbed() may load the 3.4GB model.", flush=True)
        embed = WordEmbed()

    osm = OSM(hist_len=CFG.hist_len, grid_size=CFG.grid_size, device=device).to(device)
    omt = OMTTransformer(d_model=300, nhead=4, num_layers=1, device=device).to(device)

    # target: GarbageCan only
    targets_gc = dict(TARGETS)
    targets_gc["Kitchen"] = ["GarbageCan"]

    env = ThorObjNavEnv(
        scenes=KITCHEN_SCENES,
        targets_by_room=targets_gc,
        resnet=resnet,
        embed=embed,
        osm=osm,
        omt=omt,
        device=device,
        headless=False,  # demo needs rendering
    )
    return env


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--w2v-table",
        type=str,
        default=None,
        help="Path to precomputed w2v table (.npz) generated by get_all_w2v.py",
    )
    parser.add_argument(
        "--model",
        type=str,
        default="ppo_omt4_thor.zip",
        help="Path to a trained PPO model zip",
    )
    parser.add_argument("--sleep", type=float, default=0.2, help="Seconds to sleep between steps for visualization")
    parser.add_argument("--max-steps", type=int, default=300, help="Max steps for the demo rollout")
    args = parser.parse_args()

    # ---- choose random kitchen (only for printing; env will sample its own start on reset) ----
    scene = random.choice(KITCHEN_SCENES)
    print(f"[DEMO] Example scene = {scene}, Goal = GarbageCan")

    # ---- override config for demo ----
    CFG.headless = False  # must render
    CFG.max_steps = int(args.max_steps)

    env = DummyVecEnv([lambda: make_demo_env(args.w2v_table)])

    # ---- load trained policy ----
    model = PPO.load(
        args.model,
        env=env,
        device="cuda" if torch.cuda.is_available() else "cpu",
    )

    obs = env.reset()

    step = 0
    done = False

    print("[DEMO] Starting rollout...")
    while not done:
        action, _ = model.predict(obs, deterministic=True)
        obs, reward, dones, infos = env.step(action)

        step += 1
        done = bool(dones[0])
        info = infos[0] if len(infos) > 0 else {}

        print(
            f"[STEP {step:03d}] action={int(action[0])} "
            f"reward={reward[0]:+.3f} "
            f"done={done} "
            f"visible={info.get('episode_ever_visible', False)} "
            f"min_dist={float(info.get('episode_min_dist', float('nan'))):.3f}"
        )

        if args.sleep > 0:
            time.sleep(float(args.sleep))

        if step >= CFG.max_steps:
            print("[DEMO] Max steps reached.")
            break

    print("[DEMO] Episode finished.")
    env.close()


if __name__ == "__main__":
    main()
